error_page 403 @forbidden_ip_request_json_response;
error_page 401 @forbidden_agent_request_json_response;

location @forbidden_ip_request_json_response {
    default_type application/json;
    return 403 '{"data": {"message": "", "payload": ""}, "metaData": {"error": "Forbidden", "errorCode":"403"}}';
}

location @forbidden_agent_request_json_response {
    default_type application/json;
    return 401 '{"data": {"message": "", "payload": ""}, "metaData": {"error": "Unauthorized Access", "errorCode":"401"}}';
}