server {
    # For https
    listen 443 ssl;
    # listen [::]:4460 ssl ipv6only=on;
    ssl_certificate /etc/nginx/ssl/bazzarify.com.pem;
    ssl_certificate_key /etc/nginx/ssl/bazzarify.com.key;
    server_name admin.bazzarify.local 
                vendor.bazzarify.local 
                vendor.bazzarify.com 
                admin.bazzarify.com 
                vendor.bazarify.com.np 
                consumer.bazarify.com.np;
    include /etc/nginx/conf.d/index.conf;
    location / {
        proxy_pass http://vendor:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    access_log  /var/log/nginx/vendor.access.log compression;
    error_log   /var/log/nginx/vendor.error.log warn;
}

server {
    # For https
    listen 443 ssl;
    # listen [::]:4460 ssl ipv6only=on;
    ssl_certificate /etc/nginx/ssl/bazzarify.com.pem;
    ssl_certificate_key /etc/nginx/ssl/bazzarify.com.key;
    server_name bazzarify.local 
                www.bazzarify.local 
                consumer.bazzarify.local 
                bazzarify.com 
                consumer.bazzarify.com 
                www.bazzarify.com
                consumer.bazarify.com.np 
                bazarify.com.np
                www.bazarify.com.np;
    include /etc/nginx/conf.d/index.conf;
    location / {
        proxy_pass http://consumer:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    access_log  /var/log/nginx/consumer.access.log compression;
    error_log   /var/log/nginx/consumer.error.log;
}