server {
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    
    listen 80;
    listen [::]:80;
    
    # For HTTPS
    listen 443 ssl;
    listen [::]:4460 ssl ipv6only=on;
    ssl_certificate /etc/nginx/ssl/bazzarify.pem;
    ssl_certificate_key /etc/nginx/ssl/bazzarify-key.pem;
    
    # Restrict direct IP access
    server_name ~^(?<env>[a-z]+)-(?<country>[a-z]+)\.techbizz.local$;
    
    # Root settings
    root /var/www/public;
    index index.php index.html index.htm;

    include /etc/nginx/conf.d/ip_block_domain.conf;
    include /etc/nginx/conf.d/rate_limit.conf;
    include /etc/nginx/conf.d/location_php.conf;
    include /etc/nginx/conf.d/deny_access.conf;

    autoindex_localtime on;
    autoindex on;
    error_log /var/log/nginx/app_error.log;
    access_log /var/log/nginx/app_access.log;
}
