services:
  nginx:
    image: "${PROJECT_NAME}/nginx:1.0"
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: "${PROJECT_NAME}_nginx"
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${APP_SRC}:/var/www
      - ./nginx/log:/var/log/nginx
    networks:
      - backend

  app:
    container_name: "${PROJECT_NAME}_php"
    image: "${PROJECT_NAME}/app:0.1"
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
      args:
        PUID: ${PUID}
        PGID: ${PGID}
    restart: unless-stopped
    environment:
      PHP_MEMORY_LIMIT: "${PHP_MEMORY_LIMIT}"
      PHP_IDE_CONFIG: serverName=gravity
      XDEBUG_CONFIG: idekey=PHPSTORM
      COMPOSER_MEMORY_LIMIT: '-1'
    volumes:
      - ${APP_SRC}:/var/www
    networks:
      backend:
        aliases:
          - ${PROJECT_NAME}.test
    depends_on:
      - mysql
      - nginx

  mysql:
    container_name: "${PROJECT_NAME}_mysql"
    image: "${PROJECT_NAME}/mysql:1.0"
    build: ./mysql
    volumes:
      - ./mysql/data/project_db:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: P@$$w0rd1522
      TZ: ${TIMEZONE}
    networks:
      - backend

networks:
  backend:
    driver: bridge
