services:
  nginx:
    image: "${PROJECT_NAME}/nginx:1.0"
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: "${PROJECT_NAME}_nginx"
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/log:/var/log/nginx
    depends_on:
      - consumer
      - vendor
    networks:
      - backend
  consumer:
    container_name: "${PROJECT_NAME}_consumer"
    image: "${PROJECT_NAME}/consumer:latest"
    restart: unless-stopped
    networks:
      - backend
    ports:
      - 3000:3000
  vendor:
    container_name: "${PROJECT_NAME}_vendor"
    image: "${PROJECT_NAME}/vendor:latest"
    restart: unless-stopped
    networks:
      - backend
    ports:
      - 3001:3000

  frankenphp:
    container_name: "${PROJECT_NAME}_frankenphp"
    image: "${PROJECT_NAME}/frankenphp:latest"
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    restart: always
    environment:
      USER_AGENT_KEY: "BazzarifyConsumer"
      X_APP_KEY: "cxsQ3kyvU91Bgf7bks8dszQKdibdj83zyVOXEF99qww="
    networks:
      backend:
        aliases:
          - "local-ne.larashops.local"
    ports:
      - 8081:8081
    depends_on:
      - mysql
      - vendor
      - consumer
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ${API_SRC}/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ${API_SRC}:/app

  mysql:
    container_name: "${PROJECT_NAME}_mysql"
    image: "${PROJECT_NAME}/mysql:1.0"
    build: ./mysql
    volumes:
      - ./mysql/data/project_db:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: ${TIMEZONE}
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
